---
- hosts: all
  become: yes
  pre_tasks:

  - name: update repository index / install Updates (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repository index / install Updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: yes
    when: ansible_distribution == "Ubuntu"

  roles:
    - prometheus_ubuntu
    - prometheus_centos
